---
- name: Run recon from a container
  hosts: localhost
  connection: local
  tasks:
  - name: Grab variables from the targets file
    ansible.builtin.include_vars:
      file: config.yml
  - name: Run Recon
    community.docker.docker_container_exec:
      container: "{{ assessment_name }}"
      command: ./sf.py -s "{{ item }}" -u {{ scan_type }}
    loop: "{{ domains | union(ip_ranges) }}"
    async: "{{ scan_timeout_seconds }}"
    poll: 0 # Concurrent.
