terraform:
  proxmox_use_insecure: true
  vm_cores: 1
  vm_memory: 1024
  vm_install_guest_agent: 1
  vm_user: ubuntu
  vm_disk_size: 20G
  ssh_keys: ssh-rsa mypubkeyhere
scan_type: passive
scan_timeout_seconds: 7200
assessment_name: acme
domains:
  - idontexist.home.arpa
ip_ranges:
  - 192.168.1.1/32