---
- name: Run scanning from a container
  hosts: all
  tasks:
  - name: Grab variables from the config file
    ansible.builtin.include_vars:
      file: ../config.yml
  - name: Install nmap
    ansible.builtin.apt:
      update_cache: true
      name:
        - nmap
  - name: Run port scan
    ansible.builtin.command:
      cmd: "nmap -A -oA /tmp/results {{ ip_ranges | join(' ') }}"
    register: nmap_scan
    changed_when: nmap_scan.rc == 0
  - name: Grab the results.xml file
    ansible.builtin.fetch:
      src: /tmp/results.xml
      dest: /tmp/scan_results
